### ISSUE TITLE
feature-request: Please add wp-cli

### ISSUE THREAD

**Issue by cocoonkid** [demyxsh/demyx#25]
feature-request: Please add wp-cli

**Comment by demyxco** [comment]
Hi @cocoonkid there is the `demyx wp` command but I will be adding wp-cli directly into the WordPress image itself. It's already in the works, just need to update Demyx first. Version 1.4.0 is coming out Soon™.

**Comment by cocoonkid** [comment]
thanks for considering this! looking forward to the release!

**Comment by demyxco** [comment]
Closing since wp-cli has been added many moons ago.
