### ISSUE TITLE
Add option to use PHP 8.1 instead of PHP 7.4

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [demyxsh/demyx#26]
I believe it should be useful when using the OpenLiteSpeed stack to have the option to use PHP v8.1 instead of PHP 7.4, to enable better performance.

**Comment by demyxco** [comment]
Good idea. I should add both lsphp74 and lsphp80 in the Dockerfile.

**Comment by Theofilos-Chamalis** [comment]
Any updates on PHP 8.1 or even PHP 8.2 support? It would be nice to have it irrespectable of which web server is used for additional performance especially on low end systems

**Comment by demyxco** [comment]
@Theofilos-Chamalis still in the works, PHP versions will be interchangeable via docker-compose.yml .env file or via a demyx command.
