### ISSUE TITLE
SSL certificate appears as self-signed

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [demyxsh/demyx#27]
After installing demyx with `bash -c "$(curl -sL https://demyx.sh/install)"` on a VPS that has all incoming and outgoing ports open and a DNS A record in Cloudflare pointing to its public IP, when accessing the domain using HTTPS, it appears to be self-signed (Your connection is not private / NET::ERR_CERT_AUTHORITY_INVALID error) in Chrome

**Comment by demyxco** [comment]
@Theofilos-Chamalis can you paste the output of `demyx log traefik -e`. Hide all sensitive information.

**Comment by Theofilos-Chamalis** [comment]
Thanks for the suggestion! The setup is now working as intended.

**Comment by Theofilos-Chamalis** [comment]
@demyxco 
It's already in my star list as it makes setting up wordpress a breeze on self hosted VPS 💯 
Looking forward to the upcoming version 😃
