### ISSUE TITLE
Updating wordpress plugins always fails after `demyx host upgrade` command has upgraded Traefik

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [demyxsh/demyx#29]
After running the `demyx host upgrade` command that has upgraded the Traefik docker container to the latest version, any Wordpress plugin update now fails. More specifically, this is what is presented in the main Wordpress dashboard page:

<img width="676" alt="Screenshot 2023-03-13 at 10 15 13" src="https://user-images.githubusercontent.com/5832054/224713091-2599e75f-c564-4982-aec9-f27555f96314.png">

and when trying to upgrade any of the Wordpress plugins, the page is stuck in maintenance mode for a couple of minutes until it gets back to its previous state, like so:

<img width="849" alt="Screenshot 2023-03-13 at 10 16 01" src="https://user-images.githubusercontent.com/5832054/224713409-3e359db7-3937-4379-b1a8-f1ef7167752b.png">

The Wordpress plugins in question are:
1. Elementor
2. Wordfence
3. Starter Templates
4. WP Forms

**Comment by demyxco** [comment]
Hello, apologies for the LONG delay. Getting my life on track and just released a new version of Demyx. With that said, I'm assuming you're not having this issue anymore?

**Comment by Theofilos-Chamalis** [comment]
Thanks for the reply! Hope everything's going well for you and your family. Unfortunately the issue still persists and it also affects Theme updates. The only thing that I am able to update successfully is the Wordpress version. Any other plugin/theme update fails. (Theme is Astra v4.0.2 btw).

**Comment by demyxco** [comment]
I have a feeling it's just WordPress but don't know without anymore details. Are you still using Demyx?

**Comment by Theofilos-Chamalis** [comment]
Yes, demyx v1.3.1 on Ubuntu 22.04. This happened after performing `demyx host upgrade` back on March and the initial installation was performed on December if this helps. Otherwise I guess I should start from scratch.

**Comment by demyxco** [comment]
Ok let's start by doing the Demyx upgrade process and we'll go from there. Please go here to properly migrate from 1.3.x to 1.4.0: https://demyx.sh/kb/getting-started/readme/#4-toc-title
