### ISSUE TITLE
Error request

### ISSUE THREAD

**Issue by Devlop-er** [demyxsh/demyx#30]
<img width="1036" alt="Screenshot 2023-09-28 at 22 34 11" src="https://github.com/demyxsh/demyx/assets/46845666/74d60ba7-20f2-44c9-986c-b7268f703dc0">

Once launch first command the request made is never made.

Thanks for your script and your help

**Comment by demyxco** [comment]
Docker hub issues on their [end](https://www.dockerstatus.com/pages/incident/533c6539221ae15e3f000031/6515dbc89fabff05350ae18d). It'll be up shortly.
