### ISSUE TITLE
Could not delete backup

### ISSUE THREAD

**Issue by lifeneatify** [demyxsh/demyx#35]
Hi

I checked the backup command however there seems no way to delete existing backups, this might become troublesome if the server has limited storage.

```
$ demyx help backup

demyx backup <app> <args>             Backs up app's WordPress, code-server, MariaDB, logs, and SFTP volumes
             all                      Backup all apps
                   -c                 Backup configs only
                   -d                 Backup database only
                   -l                 List an app's backups
                   --path             Save backups to a specific path
```

Could you tell how can we delete existing backups?

Thanks.

**Comment by demyxco** [comment]
Hi,

That's a good first question. There's currently no command to delete current backups but I will add that on my todo list. To delete existing backups, you'll have to go inside the demyx container using `demyx shell` then `cd /demyx/backup/wp/<app>` then delete whatever backups you need to from there.

**Comment by demyxco** [comment]
I think this issue has been solved. I will now close this now but feel free to open a new one when needed. Also please come join us at our [Discord](https://demyx.sh/discord), no pressure.
